import Provider from "@src/components/fan_guest/Provider";
import Navbar from "@/src/components/fan_guest/Navbar";
import Footer from "@/src/components/fan_guest/Footer";

export const metadata = {
  title: "EgyptCheer",
  description:
    "Join the roar of the crowd with EgyptCheer! Your go-to platform for reserving tickets to witness top-class football in the Egyptian Premier League.Generated by create next app",
};

export default function FanLayout({ children }) {
  return (
    <Provider>
      <Navbar />
      {children}
      <Footer />
    </Provider>
  );
}
