import Sidebar from "@components/admin_manager/Sidebar";
import Provider from "@src/components/fan_guest/Provider";

export const metadata = {
  title: "EgyptCheer",
  description:
    "Join the roar of the crowd with EgyptCheer! Your go-to platform for reserving tickets to witness top-class football in the Egyptian Premier League.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="business">
      <Provider>
        <body>
          {/* Side bar component */}
          <Sidebar />
          <div className="md:ml-72 mt-5 p-5">{children}</div>
        </body>
      </Provider>
    </html>
  );
}
